name: en_mi_ciudad
description: "Una app de eventos locales en Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.2.15

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/EMC.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  # Para íconos adaptativos en Android
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  # Color de fondo mientras se muestra el splash
  color: "#FFFFFF"

  # Imagen centrada (EMC.png)
  image: "assets/EMC.png"

  android: true
  ios: true

  # Ajusta cómo se escalará la imagen:
  android_gravity: fill         # Ocupa toda la pantalla
  ios_content_mode: scaleAspectFill  # Escala y recorta si hace falta
